kind: pipeline
name: testing

steps:
# 將一些不需要重複 build 的檔案 cache 起來 e.g. gem, node_module
# - name: restore-cache
#   image: drillster/drone-volume-cache
#   restore: true
#   mount:
#     - ./vendor
#   # Mount the cache volume, needs "Trusted" test
#   volumes:
#   - name: bundle
#     path: /tmp/cache/bundle

- name: install
  image: ruby:2.6.3
  group: testing
  volumes:
    - name: bundle
      path: /tmp/cache/bundle
  environment:
    RAILS_ENV: test
    RAKE_ENV: test
  commands:
  - ruby -v
  - gem -v
  - gem install bundler
  - bundle -v
  # bundle 檔案位置指定在 /usr/local/bundle
  - bundle check --path=/tmp/cache/bundle || bundle install --path=/tmp/cache/bundle --jobs=4 --retry=3

  # config
  - cp config/database.ci.yml config/database.yml

  # setup secrets and db migration
  - bundle exec rails -v
  - bundle exec rake db:create db:migrate --trace

- name: rspec
  image: ruby:2.6.3
  group: testing
  volumes:
    - name: bundle
      path: /tmp/cache/bundle
  environment:
    RAILS_ENV: test
    RAKE_ENV: test
  commands:
  - gem install bundler
  - bundle check --path=/tmp/cache/bundle || bundle install --path=/tmp/cache/bundle --jobs=4 --retry=3

  - bundle exec rails -v
  - echo $RAILS_ENV
  - echo $RAKE_ENV
  - bundle exec rspec --color #--tag ~@feature

# - name: rebuild-cache
#   image: drillster/drone-volume-cache
#   group: cleanup
#   rebuild: true
#   mount:
#     - ./vendor
#   # Mount the cache volume, needs "Trusted"
#   volumes:
#   - name: bundle
#     path: /tmp/cache/bundle

- name: discord
  image: azraeil/drone-discord
  group: notify
  pull: always
  settings:
    webhook_id:
      from_secret: discord_webhook_id
    webhook_token:
      from_secret: discord_webhook_token
  when:
    status:
    - success
    - failure

services:
- name: db
  image: mysql:5.7
  ports:
  - 3306
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

volumes:
  - name: bundle
    temp: {}
