kind: pipeline
name: testing

steps:
- name: install
  image: ruby:2.6.3
  group: testing
  environment:
    RAILS_ENV: test
    RAKE_ENV: test
  commands:
  - ruby -v
  - gem -v
  - gem install bundler
  - bundle -v
  # bundle，檔案位置設定在 vendor/bundle
  - bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
  - bundle exec rails -v
  - bundle exec rake db:create db:migrate --trace

- name: rspec
  image: ruby:2.6.3
  group: testing
  environment:
    RAILS_ENV: test
    RAKE_ENV: test
  commands:
  - gem install bundler
  - bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
  - bundle exec rails -v
  - echo $RAILS_ENV
  - echo $RAKE_ENV
  - bundle exec rspec --color #--tag ~@feature

services:
- name: db
  image: mysql:5.7
  ports:
  - 3306
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
